### ISSUE TITLE
Postgres Database Connection Issue

### ISSUE THREAD

**Issue by WingZer0o** [Cryptographic-API-Services/discord-bot#6]
```shell
at Connection.#readMessage (https://deno.land/x/postgres@v0.19.3/connection/connection.ts:186:13)
0|chatbot  |     at eventLoopTick (ext:core/01_core.js:168:7)
0|chatbot  |     at async Connection.#preparedQuery (https://deno.land/x/postgres@v0.19.3/connection/connection.ts:953:25)
0|chatbot  |     at async Connection.query (https://deno.land/x/postgres@v0.19.3/connection/connection.ts:979:18)
0|chatbot  |     at async PoolClient.#executeQuery (https://deno.land/x/postgres@v0.19.3/client.ts:256:12)
0|chatbot  |     at async PoolClient.queryArray (https://deno.land/x/postgres@v0.19.3/client.ts:339:12)
0|chatbot  | error: Uncaught (in promise) ConnectionError: The session was terminated unexpectedly
0|chatbot  |       throw new ConnectionError("The session was terminated unexpectedly");
0|chatbot  |             ^
0|chatbot  |     at Connection.#readMessage (https://deno.land/x/postgres@v0.19.3/connection/connection.ts:186:13)
0|chatbot  |     at eventLoopTick (ext:core/01_core.js:168:7)
0|chatbot  |     at async Connection.#preparedQuery (https://deno.land/x/postgres@v0.19.3/connection/connection.ts:953:25)
0|chatbot  |     at async Connection.query (https://deno.land/x/postgres@v0.19.3/connection/connection.ts:979:18)
0|chatbot  |     at async PoolClient.#executeQuery (https://deno.land/x/postgres@v0.19.3/client.ts:256:12)
0|chatbot  |     at async PoolClient.queryArray (https://deno.land/x/postgres@v0.19.3/client.ts:339:12)
```

**Comment by WingZer0o** [comment]
https://github.com/denodrivers/postgres/issues/483

**Comment by WingZer0o** [comment]
https://www.gnugk.org/keepalive.html

**Comment by WingZer0o** [comment]
Should just try with a local database. This schema will need to be recreated.

**Comment by WingZer0o** [comment]
I switched him over to a new database locally on the Ubuntu machine instead of the cloud database service Neon. I went to the bar and grabbed a beer for about 45-50 minutes and he still works. I will close this for now and update the ticket as needed. The timeout was occurring every 20-25 minutes prior to local install.
